# kanata-tray configuration
# For help see https://github.com/rszyma/kanata-tray/blob/main/README.md
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/v0.7.1/doc/config_schema.json"

general.allow_concurrent_presets = false
defaults.tcp_port = 5829

[defaults.hooks]
# Hooks allow running custom commands on specific events
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]

[presets.'Default Preset']
kanata_executable = '/opt/homebrew/bin/kanata'
kanata_config = '/Users/jacebabin/.config/kanata/kanata.kbd'
autorun = true
